from .department_service_dependency import get_department_service
from .department_connection_service_dependency import get_department_connection_service

__all__ = ["get_department_service", "get_department_connection_service"]
