"""agregar_tabla_caserios

Revision ID: 287e1f12b6c1
Revises: aa4f777b6bb2
Create Date: 2025-03-26 15:27:49.686471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '287e1f12b6c1'
down_revision: Union[str, None] = 'aa4f777b6bb2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('caserios',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('nombre', sa.TEXT(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('centro_poblado_id', sa.BIGINT(), nullable=True),
    sa.CheckConstraint('LENGTH(nombre) > 3', name='ck_caserio_name'),
    sa.ForeignKeyConstraint(['centro_poblado_id'], ['centros_poblados.id'], name='fk_caserios_centro_poblados', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('caserios')
    # ### end Alembic commands ###
