"""agregar_tabla_comunicacion_areas

Revision ID: 34cdd29f21de
Revises: 287e1f12b6c1
Create Date: 2025-03-31 16:18:10.762588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34cdd29f21de'
down_revision: Union[str, None] = '287e1f12b6c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comunicacion_areas',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('area_origen_id', sa.BIGINT(), nullable=False),
    sa.Column('area_destino_id', sa.BIGINT(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['area_destino_id'], ['areas.id'], name='fk_comunicacion_areas_area_destino', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['area_origen_id'], ['areas.id'], name='fk_comunicacion_areas_area_origen', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('area_origen_id', 'area_destino_id', name='uq_comunicacion_areas_area_origen_area_destino')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comunicacion_areas')
    # ### end Alembic commands ###
