"""agregar_tabla_remitentes

Revision ID: 37ab045a3d1c
Revises: 8e62b7fb17e7
Create Date: 2025-03-24 10:55:08.079697

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37ab045a3d1c'
down_revision: Union[str, None] = '8e62b7fb17e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('remitentes',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('dni', sa.BIGINT(), nullable=False),
    sa.Column('apellido_paterno', sa.TEXT(), nullable=False),
    sa.Column('apellido_materno', sa.TEXT(), nullable=False),
    sa.Column('nombres', sa.TEXT(), nullable=False),
    sa.Column('genero', sa.TEXT(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("genero IN ('Masculino', 'Femenino')", name='ck_remitente_genero_values'),
    sa.CheckConstraint('LENGTH(apellido_materno) > 3', name='ck_remitente_apellido_materno'),
    sa.CheckConstraint('LENGTH(apellido_paterno) > 3', name='ck_remitente_apellido_paterno'),
    sa.CheckConstraint('LENGTH(nombres) > 3', name='ck_remitente_nombres'),
    sa.CheckConstraint('dni >= 10000000 AND dni <= 99999999', name='ck_remitente_dni_range'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dni')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('remitentes')
    # ### end Alembic commands ###
