"""agregar_tabla_ambito

Revision ID: 842df5a6264c
Revises: 68134bc8c00c
Create Date: 2025-03-20 10:24:07.981196

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '842df5a6264c'
down_revision: Union[str, None] = '68134bc8c00c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ambitos',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('nombre', sa.TEXT(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('LENGTH(nombre) > 3', name='ck_ambito_name'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ambitos')
    # ### end Alembic commands ###
