"""agregar_tabla_centros_poblados

Revision ID: 8e62b7fb17e7
Revises: 842df5a6264c
Create Date: 2025-03-21 09:54:41.017671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e62b7fb17e7'
down_revision: Union[str, None] = '842df5a6264c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('centros_poblados',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('nombre', sa.TEXT(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('LENGTH(nombre) < 100', name='ck_centro_poblado_name_length'),
    sa.CheckConstraint('LENGTH(nombre) > 3', name='ck_centro_poblado_name'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('centros_poblados')
    # ### end Alembic commands ###
