"""agregar_tabla_trabajadores

Revision ID: aa4f777b6bb2
Revises: 9e9ed051533c
Create Date: 2025-03-25 09:00:31.958911

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa4f777b6bb2'
down_revision: Union[str, None] = '9e9ed051533c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trabajadores',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('dni', sa.BIGINT(), nullable=False),
    sa.Column('apellido_paterno', sa.TEXT(), nullable=False),
    sa.Column('apellido_materno', sa.TEXT(), nullable=False),
    sa.Column('nombres', sa.TEXT(), nullable=False),
    sa.Column('genero', sa.TEXT(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cargo_id', sa.BIGINT(), nullable=False),
    sa.Column('area_id', sa.BIGINT(), nullable=False),
    sa.CheckConstraint("genero IN ('Masculino', 'Femenino')", name='ck_trabajador_genero_valido'),
    sa.CheckConstraint('LENGTH(apellido_materno) > 3', name='ck_trabajador_apellido_materno'),
    sa.CheckConstraint('LENGTH(apellido_paterno) > 3', name='ck_trabajador_apellido_paterno'),
    sa.CheckConstraint('LENGTH(nombres) > 3', name='ck_trabajador_nombres'),
    sa.CheckConstraint('dni >= 10000000 AND dni <= 99999999', name='ck_trabajador_dni_8digitos'),
    sa.ForeignKeyConstraint(['area_id'], ['areas.id'], name='fk_trabajadores_areas', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['cargo_id'], ['cargos.id'], name='fk_trabajadores_cargo', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dni')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trabajadores')
    # ### end Alembic commands ###
