"""add_documents_table

Revision ID: e51cd95457a8
Revises: e808eae2deb4
Create Date: 2025-04-09 16:05:53.096730

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e51cd95457a8'
down_revision: Union[str, None] = 'e808eae2deb4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('registration_code', sa.TEXT(), nullable=True),
    sa.Column('title', sa.TEXT(), nullable=False),
    sa.Column('subject', sa.TEXT(), nullable=False),
    sa.Column('pages', sa.BIGINT(), nullable=False),
    sa.Column('storage_path', sa.TEXT(), nullable=False),
    sa.Column('size', sa.BIGINT(), nullable=False),
    sa.Column('submitter_id', sa.BIGINT(), nullable=False),
    sa.Column('document_category_id', sa.BIGINT(), nullable=False),
    sa.Column('documentary_topic_id', sa.BIGINT(), nullable=False),
    sa.Column('hamlet_id', sa.BIGINT(), nullable=True),
    sa.Column('settlement_id', sa.BIGINT(), nullable=False),
    sa.Column('registered_by_user_id', sa.BIGINT(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('LENGTH(registration_code) = 20', name='ck_document_registration_code'),
    sa.CheckConstraint('LENGTH(subject) > 3', name='ck_document_subject'),
    sa.CheckConstraint('LENGTH(title) > 3', name='ck_document_title'),
    sa.CheckConstraint('pages > 0', name='ck_document_pages'),
    sa.ForeignKeyConstraint(['document_category_id'], ['document_categories.id'], name='fk_documents_document_category', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['documentary_topic_id'], ['documentary_topics.id'], name='fk_documents_documentary_topic', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['hamlet_id'], ['hamlets.id'], name='fk_documents_hamlet', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['registered_by_user_id'], ['users.id'], name='fk_documents_user', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['settlement_id'], ['settlements.id'], name='fk_documents_settlement', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['submitter_id'], ['submitters.id'], name='fk_documents_submitter', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('registration_code'),
    sa.UniqueConstraint('title')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('documents')
    # ### end Alembic commands ###
