"""partial_schema_70percent_complete

Revision ID: e808eae2deb4
Revises: 
Create Date: 2025-04-03 10:06:29.432343

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e808eae2deb4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('name', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('LENGTH(name) > 3', name='ck_department_name'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('document_categories',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('name', sa.TEXT(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('LENGTH(name) > 3', name='ck_document_category_name'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('documentary_topics',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('name', sa.TEXT(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('LENGTH(name) > 3', name='ck_topic_name'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('positions',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('name', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('LENGTH(name) > 3', name='ck_position_name'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('roles',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('name', sa.TEXT(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('LENGTH(name) > 3', name='ck_role_name'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('settlements',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('name', sa.TEXT(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('LENGTH(name) < 100', name='ck_settlement_name_length'),
    sa.CheckConstraint('LENGTH(name) > 3', name='ck_settlement_name'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('submitters',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('dni', sa.BIGINT(), nullable=False),
    sa.Column('paternal_surname', sa.TEXT(), nullable=False),
    sa.Column('maternal_surname', sa.TEXT(), nullable=False),
    sa.Column('names', sa.TEXT(), nullable=False),
    sa.Column('gender', sa.TEXT(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("gender IN ('Male', 'Female')", name='ck_submitter_gender_values'),
    sa.CheckConstraint('LENGTH(maternal_surname) > 3', name='ck_submitter_maternal_surname'),
    sa.CheckConstraint('LENGTH(names) > 3', name='ck_submitter_names'),
    sa.CheckConstraint('LENGTH(paternal_surname) > 3', name='ck_submitter_paternal_surname'),
    sa.CheckConstraint('dni >= 10000000 AND dni <= 99999999', name='ck_submitter_dni_range'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dni')
    )
    op.create_table('department_connections',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('source_department_id', sa.BIGINT(), nullable=False),
    sa.Column('target_department_id', sa.BIGINT(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['source_department_id'], ['departments.id'], name='fk_department_connections_source', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_department_id'], ['departments.id'], name='fk_department_connections_target', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_department_id', 'target_department_id', name='uq_department_connections_source_target')
    )
    op.create_table('employees',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('dni', sa.BIGINT(), nullable=False),
    sa.Column('paternal_surname', sa.TEXT(), nullable=False),
    sa.Column('maternal_surname', sa.TEXT(), nullable=False),
    sa.Column('names', sa.TEXT(), nullable=False),
    sa.Column('gender', sa.TEXT(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('position_id', sa.BIGINT(), nullable=False),
    sa.Column('department_id', sa.BIGINT(), nullable=False),
    sa.CheckConstraint("gender IN ('Male', 'Female')", name='ck_employee_gender_valid'),
    sa.CheckConstraint('LENGTH(maternal_surname) > 3', name='ck_employee_maternal_surname'),
    sa.CheckConstraint('LENGTH(names) > 3', name='ck_employee_names'),
    sa.CheckConstraint('LENGTH(paternal_surname) > 3', name='ck_employee_paternal_surname'),
    sa.CheckConstraint('dni >= 10000000 AND dni <= 99999999', name='ck_employee_dni_8digits'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name='fk_employees_department', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['position_id'], ['positions.id'], name='fk_employees_position', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dni')
    )
    op.create_table('hamlets',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.TEXT(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('settlement_id', sa.BIGINT(), nullable=True),
    sa.CheckConstraint('LENGTH(name) > 3', name='ck_hamlet_name'),
    sa.ForeignKeyConstraint(['settlement_id'], ['settlements.id'], name='fk_hamlets_settlement', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('username', sa.TEXT(), nullable=False),
    sa.Column('password', sa.TEXT(), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('role_id', sa.BIGINT(), nullable=False),
    sa.Column('employee_id', sa.BIGINT(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('LENGTH(password) >= 8', name='ck_user_password'),
    sa.CheckConstraint('LENGTH(username) > 3', name='ck_user_username'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name='fk_users_employees', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name='fk_users_roles', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('hamlets')
    op.drop_table('employees')
    op.drop_table('department_connections')
    op.drop_table('submitters')
    op.drop_table('settlements')
    op.drop_table('roles')
    op.drop_table('positions')
    op.drop_table('documentary_topics')
    op.drop_table('document_categories')
    op.drop_table('departments')
    # ### end Alembic commands ###
